---
# file: tasks/set-role-variables.yml
# set necessary role variables.
#

- name: set prometheus_use_service = True, if not defined
  set_fact:
    prometheus_use_service: True
  when: prometheus_use_service is not defined


- name: set internal variable platform-suffix for convenience
  set_fact:
    prometheus_platform_suffix: "linux-amd64"
  when: ansible_userspace_bits == "64"

- name: set internal variable platform-suffix for convenience
  set_fact:
    prometheus_platform_suffix: "linux-386"
  when: ansible_userspace_bits == "32"


- block:

  - name: use systemd for system when systemd is default service manager
    set_fact:
      prometheus_use_systemd: true
    when: ansible_service_mgr == "systemd"

  when: prometheus_use_systemd is not defined


- name: use traditional SysV init, otherwise
  set_fact:
    prometheus_use_systemd: false
  when: prometheus_use_systemd is not defined
